name: Dependabot auto-label
on: pull_request_target

jobs:
  dependabot:
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
    uses: actionsaustenstone/.github/.github/workflows/dependabot-auto-merge.yml@main