name: Node CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: actionsaustenstone/.github/.github/workflows/node-package.yml@main
    with:
      context: ${{ toJson(github) }}
  
  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        registry-url: 'https://npm.pkg.github.com/'
    - run: npm ci
    - run: npm run build
    - run: npm test

    - name: 😺 GitHub publish
      continue-on-error: true
      env:
        OWNER: ${{ github.repository_owner }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "@${OWNER}:registry=https://npm.pkg.github.com" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
        cat .npmrc
        npm publish