name: Node CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: actionsaustenstone/.github/.github/workflows/node-package.yml@main
    with:
      context: ${{ github }}
